name: Running tests

on: push

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Chrome
      run: |
        brew install --cask google-chrome

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade pytest pytest-html

    - name: Set execute permissions for arm-64
      run: |
        if [[ $(uname -m) == "arm64" ]]; then
          chmod +x resources/arm64
        fi

    - name: Run tests
      run: |
        python -m pytest
