name: Selenium Tests on macOS M1

on: push

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Chrome and WebDriver
      run: |
        brew install --cask google-chrome
        brew install --cask chromedriver

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade pytest pytest-html

    - name: Run tests
      run: |
        python -m pytest
