name: Selenium Tests on macOS x86_64

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    env:
      DEV_URL: ${{ secrets.DEV_URL }}
      STAG_URL: ${{ secrets.STAG_URL }}

    permissions:
      checks: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Chrome and WebDriver
      run: |
        brew install --cask google-chrome

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade pytest pytest-html
      working-directory: ${{ github.workspace }}

    - name: Run tests
      run: |
        python -m pytest --verbose --junit-xml=test-results.xml
      working-directory: ${{ github.workspace }}

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/test-results.xml'
        detailed_summary: true
        include_passed: true
